---
development:
  cloud_name: phuaky
  api_key: '269159583845777'
  api_secret: 5kQR8Uiwuf1HeKdTWWMDPf71QJY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: phuaky
  api_key: '269159583845777'
  api_secret: 5kQR8Uiwuf1HeKdTWWMDPf71QJY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: phuaky
  api_key: '269159583845777'
  api_secret: 5kQR8Uiwuf1HeKdTWWMDPf71QJY
  enhance_image_tag: true
  static_image_support: false
